### ISSUE TITLE
真的不错！！想请问下后端代码有开源吗？

### ISSUE THREAD

**Issue by chenshuangwu** [wangyuan389/mall-cook#10]
你好，我想自己搭建一个，需要用到后端代码，请问有打算开源吗？谢谢。

**Comment by wangyuan389** [comment]
你好，后端只是我用node写的几个简单的演示接口，没什么值得开源出来的。
后面我会出份api文档，大佬可以自己写

**Comment by chenshuangwu** [comment]
OK，十分感谢！！！

**Comment by 6025jie** [comment]
> 你好，后端只是我用node写的几个简单的演示接口，没什么值得开源出来的。 后面我会出份api文档，大佬可以自己写

大佬，后端node项目开源到哪里了  没看到呢
