### ISSUE TITLE
求教,2022年10月左右就学习过一段时间,后来因为工作,就没怎么用过.现在发现不会用了.

### ISSUE THREAD

**Issue by steam15231925220** [wangyuan389/mall-cook#102]
我是一名自学的后端,基础不扎实.但是对这个很感兴趣.希望可以帮助我一下.我不胜感激......

**Comment by steam15231925220** [comment]
172.16.180.79 未发送任何数据。

**Comment by steam15231925220** [comment]
1. 大陆内gitee.com 的文档和体验网址全部无法访问
2. clone 到本地的服务虽然可以正常install 但是无法正常打开网页.(疑似大陆服务器崩溃)
3. node服务器yarn install 2/4 第139个包无法正常下载.
4. 魔法到github后,http://139.196.223.93:4000/#虽然可以打开.但是制作页面的组件无法正常使用.
5. schema可以正常使用.
6.

**Comment by Qiu-Jun** [comment]
> 1. 大陆内gitee.com 的文档和体验网址全部无法访问
> 
> 2. clone 到本地的服务虽然可以正常install 但是无法正常打开网页.(疑似大陆服务器崩溃)
> 
> 3. node服务器yarn install 2/4 第139个包无法正常下载.
> 
> 4. 魔法到github后,http://139.196.223.93:4000/#虽然可以打开.但是制作页面的组件无法正常使用.
> 
> 5. schema可以正常使用.
> 
> 6. 

Can好像挂了，周一作者会把cdn去掉，把资源都放服务器

**Comment by steam15231925220** [comment]
> > 1. 大陆内 gitee.com 的文档和体验网址全部无法访问
> > 2. clone 到本地的服务虽然可以正常install 但是无法正常打开网页.(疑似大陆服务器崩溃)
> > 3. node服务器yarn install 2/4 第139个包无法正常下载.
> > 4. 魔法到github后，[http://139.196.223.93:4000/#虽然可以打开.但是制作页面的组件无法正常使用](http://139.196.223.93:4000/#%E8%99%BD%E7%84%B6%E5%8F%AF%E4%BB%A5%E6%89%93%E5%BC%80.%E4%BD%86%E6%98%AF%E5%88%B6%E4%BD%9C%E9%A1%B5%E9%9D%A2%E7%9A%84%E7%BB%84%E4%BB%B6%E6%97%A0%E6%B3%95%E6%AD%A3%E5%B8%B8%E4%BD%BF%E7%94%A8).
> > 5. schema可以正常使用.
> 
> Can好像挂了，周一作者会把cdn去掉，把资源都放服务器

感谢您的回复,我会持续关注这个问题,谢谢您的帮助.
