### ISSUE TITLE
页面实时预览时，布局错乱

### ISSUE THREAD

**Issue by iiuhuy** [wangyuan389/mall-cook#23]
![image](https://user-images.githubusercontent.com/21032217/161020829-fc5e48de-df25-4e68-928e-e8e7570fd465.png)

**Comment by wangyuan389** [comment]
![1648725877(1)](https://user-images.githubusercontent.com/44593297/161044433-0d6c1b3e-b7a0-4ada-ab24-9486da332f98.jpg)
fu'yan复验正常，可能原因是预览界面是iframe嵌套H5项目，网络导致iframe加载未生效

**Comment by wangyuan389** [comment]
外框样式错乱已修复
