### ISSUE TITLE
关于微信二维码预览的疑问

### ISSUE THREAD

**Issue by Fuyun791** [wangyuan389/mall-cook#37]
我看二维码都是指向mall-cook小程序的，是保存了json数据，然后做了个渲染吗？

有做什么用户层面的数据保存吗？

如果我保存了一个，然后另一个也保存了。我会看到另一个做出保存，生成的小程序ui吗？

**Comment by wangyuan389** [comment]
小程序扫码时，会传递商城id，然后查询配置数据渲染页面
