### ISSUE TITLE
想利用这个平台做数据可视化，请问可以支持一下 echarts 组建吗

### ISSUE THREAD

**Issue by playniuniu** [wangyuan389/mall-cook#4]
非常棒的项目，想利用这个平台做数据可视化，请问可以支持一下 echarts 组建吗

**Comment by wangyuan389** [comment]
小哥，导echarts组件当然可以。
我下午刚决定在项目新建shelf分支，从零重构一套"干净"的可视化架构，同时会在掘金同步出教程文章详细讲述关键功能点，预计半个月内开始。不知道你着急吗？如果不急你可以跟着教程自己写一套。

**Comment by playniuniu** [comment]
非常感谢，期待您的教程
