### ISSUE TITLE
本地开发启动后mall-cook h5无法进入首页

### ISSUE THREAD

**Issue by labike** [wangyuan389/mall-cook#41]
按照官网文档配置数据库后, 设置本地开发环境，启动后选择mall-cook h5无法进入首页?

本地开发环境:
```
export default {
  baseApi: 'http://127.0.0.1:3000/', // 'https://www.lanshan-h5.cn:1443/node/',  // 后端接口地址
  viewUrl: 'http://192.168.0.123:8081/#/' // 'http://110.42.184.128:9000/#/'          // iframe嵌套的H5地址,本地开发可改为本地启动的H5地址
}
```

`yarn run dev`后是这样的:
![1649820522(1)](https://user-images.githubusercontent.com/15871933/163094339-25593372-af79-4c61-874c-c5c05882a7b4.png)
![1649820594(1)](https://user-images.githubusercontent.com/15871933/163094464-19d63cb4-3ee7-42fa-a0ed-d51bcd649cea.png)

是哪里没配置对吗？

**Comment by wangyuan389** [comment]
没传递id，无法查询配置数据渲染，已更新增加警告，拉取最新代码。
文档里有修改iframe配置路径，替换h5地址，仔细观看

**Comment by forever14998** [comment]
mall-cook-template 模块中， src/tuils/request.js 文件需要替换下本地服务的路径，不然查询不出来数据

**Comment by labike** [comment]
@wangyuan389 @forever14998 感谢！！！
