### ISSUE TITLE
请问各子项目用途

### ISSUE THREAD

**Issue by 1455668754** [wangyuan389/mall-cook#42]
![image](https://user-images.githubusercontent.com/88491446/163336885-dcdc7ccf-7077-44dc-8a3b-01b0460e26d0.png)
作者大大你好，请问这两个子项目，哪个是用于后台编辑页面，哪个是用于移动端的

**Comment by wangyuan389** [comment]
上一个是后台，下一个是uniapp渲染引擎渲染移动端

**Comment by 1455668754** [comment]
同时还可以请问下，后端这边迁移到vue3项目的化，改动内容大吗（疑虑原有的样式这些会受影响吗）

**Comment by wangyuan389** [comment]
和其他vue2迁移3的改动一样，没什么特别的

**Comment by 1455668754** [comment]
请问大佬有后台的目录结构说明吗，看的有点迷糊

**Comment by wangyuan389** [comment]
文档后期会慢慢完善，这个需要实际，毕竟个人精力有限
