### ISSUE TITLE
有没计划出vue3版本？

### ISSUE THREAD

**Issue by linqs2022** [wangyuan389/mall-cook#46]

**Comment by wangyuan389** [comment]
暂时没有，计划新低代码开源项目会使用vue3+ts，如果后期技术成熟可能会考虑重构个plus版

**Comment by cloydlau** [comment]
你好，mall-cook 的依赖 [minimce](https://github.com/cloydlau/minimce) 已率先对 vue 3 进行了支持，一套代码同时支持 vue 2 + vue 3，所以升级成本接近于0，后续 imgpond 也会考虑出 vue 3 版本。

**Comment by cloydlau** [comment]
后续：imgpond 已推出 vue 3 版本，见 https://github.com/cloydlau/kikimore#imageupload
vue 2.6/2.7/3 一体通用。
