### ISSUE TITLE
安装好依赖之后本地跑不起来

### ISSUE THREAD

**Issue by ycrao** [wangyuan389/mall-cook#5]
如题，报错：
Syntax Error: TypeError: Cannot read property 'parseComponent' of undefined

 @ ./h5/main.js 14:0-28 46:13-16

![image](https://user-images.githubusercontent.com/3280204/146708166-1879cd6b-22dc-47ef-a3e1-c8bae0200eee.png)

**Comment by wangyuan389** [comment]
![image](https://user-images.githubusercontent.com/44593297/146708534-2be39420-e791-4ed3-8104-440e1a1d650f.png)
![image](https://user-images.githubusercontent.com/44593297/146708596-776f873c-4316-4957-a3eb-fb09cb52f80f.png)
小哥,应该是你vue与vue-template-compiler依赖版本号不对，项目使用的是vue2.6

**Comment by ycrao** [comment]
感谢已经解决！
