### ISSUE TITLE
您好，在uniapp 上看到了您平台的介绍，请问这个平台是否可以商用，再有兼容性怎么样？

### ISSUE THREAD

**Issue by smallyaohailu** [wangyuan389/mall-cook#58]
![image](https://user-images.githubusercontent.com/718669/174544250-eae8c3dc-ad7c-48ab-ada3-66f9f13a625d.png)

**Comment by wangyuan389** [comment]
可商用，现在新版本渲染引擎是uni-app项目，可以兼容uni-app生成的场景，包括h5、小程序等

**Comment by smallyaohailu** [comment]
嗯嗯，感谢！
