### ISSUE TITLE
Use of Hard-coded Cryptographic Key vulnerability.

### ISSUE THREAD

**Issue by manunio** [wangyuan389/mall-cook#60]
Hi `mall-cook/packages/mall-cook-service` uses hardcoded jwt secret to sign and decode jwt tokens, which makes it vulnerable to forging token and impersonate as a valid user and it also uses `jwt.decode()` instead of `jwt.verify()` function to decode tokens, which does not validate token signature while decoding token, which also may result in token forging by attackers.

pull request with fix for above mentioned vulnerabilities https://github.com/wangyuan389/mall-cook/pull/59

see https://r2c.dev/blog/2020/hardcoded-secrets-unverified-tokens-and-other-common-jwt-mistakes/ for more details

![jwt-hardcoded-key](https://user-images.githubusercontent.com/8413800/177154272-0e7faaa5-4af8-44c2-b651-c835cb673652.png)

**Comment by wangyuan389** [comment]
thanks
