### ISSUE TITLE
Can't import the named export 'watch' from non EcmaScript module (only default export is available)

### ISSUE THREAD

**Issue by lizhuang-zhi** [wangyuan389/mall-cook#61]
当我使用 npm run dev 启动 mall-cook-platform, 我这里报了很多关于 'h', 'ref', 'watch' 之类的类似于标题的错误, 这些都是关于Vue3的东西, 但是我看大佬用的是 Vue2, 是不是这块的某个导入错误的原因, 但是我看大佬的项目里面也没有使用 'ref' 或者 ‘reactive' 这些 Vue3 的东西, 为啥还会报这个错呢? 请问大佬有遇到过吗?

![image](https://user-images.githubusercontent.com/59167582/180804716-8e3199e6-1859-41e5-bde2-77da4864f327.png)

**Comment by lizhuang-zhi** [comment]
不好意思, 大佬, 我又查资料解决了....
只需要在 vue.config.js 中的 chainWebpack 方法中 添加如下代码, 然后重新 npm run dev 就可以了
```js
  config.module
    .rule("mjs")
    .test(/\.mjs$/)
    .type("javascript/auto")
    .include.add(/node_modules/)
    .end()
```

**Comment by wangyuan389** [comment]
有插件改用了vite，已经修复了。  谢谢提醒
