### ISSUE TITLE
Mac mall-cook-platform 启动后 页面出不来

### ISSUE THREAD

**Issue by datafu** [wangyuan389/mall-cook#62]
mall-cook-platform : npm run dev
App running at:
  - Local:   http://localhost:8080 
  - Network: http://192.168.106.39:8080

  Note that the development build is not optimized.
  To create a production build, run yarn build.

2. 配置了mall-cook-platform config/.   default {
  baseApi: 'https://www.lanshan-h5.cn:1443/node/',  // 后端接口地址
  viewUrl: 'http://localhost:8080'          // iframe嵌套的H5地址,本地开发可改为本地启动的H5地址
}

3. 浏览器打开后 一直处于加载状态

**Comment by wangyuan389** [comment]
1、 拉取最新代码，下载依赖，重新启动试下
2、 如果不行，打开控制台看是否有报错，或者cdn没加载出来
