### ISSUE TITLE
minimce组件加载不出来

### ISSUE THREAD

**Issue by boncxa** [wangyuan389/mall-cook#65]
你好，麻烦问一下，minimce组件加载不出来，报如下错误，我应该怎么做，谢谢了
![image](https://user-images.githubusercontent.com/29709214/188201186-7154bab8-9dec-44f1-b6b4-3bb8391b36b5.png)

**Comment by cloydlau** [comment]
你好，无法复现。建议：
1. 拉取 mall-cook 最新代码
2. 删除 node_module，删除 yarn.lock，删除 package-lock.json
3. 重新安装依赖

> 我是 [minimce](https://github.com/cloydlau/minimce) 的维护者，如果确定是组件问题可以提到链接里面，提在这里无法第一时间看到。
