### ISSUE TITLE
作者你好，可以申请加入吗？

### ISSUE THREAD

**Issue by woodThunder** [wangyuan389/mall-cook#66]
最近也在研究低代码平台，非常感兴趣加入咱们这个大家庭

**Comment by wangyuan389** [comment]
![08b2e1c46c116d2b220c86801128282](https://user-images.githubusercontent.com/44593297/189280198-03b2ea30-8014-4ff9-9a87-c66d9f164e71.jpg)
这是我微信，你加我下，我拉你进交流群
