### ISSUE TITLE
拖拽组件，释放后的视觉优化

### ISSUE THREAD

**Issue by code-artisan** [wangyuan389/mall-cook#67]
提一个小小的优化项，拖拽组件、释放后的回弹可以优化一下不？看着有点怪。

页面设计和功能层面感觉都挺棒的，作者加油！

**Comment by wangyuan389** [comment]
谢谢支持，麻烦问下具体回弹效果是？我试了下拖拽没发现明显的回弹

**Comment by code-artisan** [comment]
其实说的是 `draggable` 属性自带的效果，虽然不影响正常使用，但看着有点怪怪的。

**Comment by wangyuan389** [comment]
不好意思，最近公司太忙忘记回复了。  draggable自带效果我感觉体验还好，我认为没必要覆盖修改。 我现在的精力主要是在进行新开源的开发，可以理解成mall-cook的plus版本，基于vue3开发，现设计会支持加载远程物料、sass物料中心、物料事件交互、构建项目出码等功能。  
感谢提意见，如果感兴趣可以等新开源再体验
