### ISSUE TITLE
商城创建构建之后，如何发布部署

### ISSUE THREAD

**Issue by semmywong** [wangyuan389/mall-cook#79]
商城创建构建之后，如何发布部署，比如怎么上传小程序到官网？

**Comment by Qiu-Jun** [comment]
小程序就用微信开发者工具打包上传啊，h5就部署到你的服务器

**Comment by Qiu-Jun** [comment]
> 商城创建构建之后，如何发布部署，比如怎么上传小程序到官网？

小程序就用微信开发者工具打包上传啊，h5就部署到你的服务器

**Comment by semmywong** [comment]
> > 商城创建构建之后，如何发布部署，比如怎么上传小程序到官网？
> 
> 小程序就用微信开发者工具打包上传啊，h5就部署到你的服务器

不好意思，我没有表达清楚，我意思需要发布上传的代码在哪里？就类似uniapp编译之后，可以把dist目录导入到微信开发者工具进行发布，这个低代码需要哪个目录导入到开发者工具
