### ISSUE TITLE
平台地址 ,文档地址失效了

### ISSUE THREAD

**Issue by pxiaolong** [wangyuan389/mall-cook#98]
平台地址 ,文档地址失效了1

**Comment by Eastboat** [comment]
会不会是服务器过期了没续费🚨

**Comment by Qiu-Jun** [comment]
> 平台地址 ,文档地址失效了1

最新消息，大佬这几天再重新部署

**Comment by Qiu-Jun** [comment]
> 平台地址 ,文档地址失效了1

http://139.196.223.93:4000/#/login

**Comment by steam15231925220** [comment]
您好,为什么我根据您的地址访问,虽然成功但是缺显示-----ip 未发送任何数据。???


> > 平台地址 ,文档地址失效了1
> 
> http://139.196.223.93:4000/#/login

**Comment by Qiu-Jun** [comment]
> 您好,为什么我根据您的地址访问,虽然成功但是缺显示-----ip 未发送任何数据。???
> 
> 
> 
> 
> 
> > > 平台地址 ,文档地址失效了1
> 
> > 
> 
> > http://139.196.223.93:4000/#/login
> 
> 
> 
> 

cdn恢复了，你试试，模板数据应该是没了

**Comment by pxiaolong** [comment]
谢谢大佬



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年12月17日(星期天) 上午7:42
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [wangyuan389/mall-cook] 平台地址 ,文档地址失效了 (Issue #98)





  
您好,为什么我根据您的地址访问,虽然成功但是缺显示-----ip 未发送任何数据。???
   
平台地址 ,文档地址失效了1
      
http://139.196.223.93:4000/#/login
   
cdn恢复了，你试试，模板数据应该是没了

**Comment by Eastboat** [comment]
@Qiu-Jun 群二维码失效，求拉，交流一下 🎉

**Comment by Qiu-Jun** [comment]
> @Qiu-Jun 群二维码失效，求拉，交流一下 🎉

我也没

**Comment by Eastboat** [comment]
> > @Qiu-Jun 群二维码失效，求拉，交流一下 🎉
> 
> 我也没

好吧，尴尬💚
